### ISSUE TITLE
ProtocolLib

### ISSUE THREAD

**Issue by boy0001** [boy0001/ExperienceBankII#13]
So a quirk of the minecraft client is if you send the sign packet before the chunk packet it prints a debug message in chat. (The client really shouldn't be printing debug messages, but we can't change that behavior).

Using ProtocolLib makes it easy to modify the sign packet without worrying about sending it too early.

**Comment by bmarwell** [comment]
I'll look into that, thanks for the hint.
I just found out that `sign.update();` needs to be called at some time.

**Comment by bmarwell** [comment]
Hmm, I wonder which event does actually trigger that debug message. Perhaps it would be wise to also include the `ChunkPopulateEvent`. Also, at no time we check for `isCancelled()`. In case this helps, we still don't need the ProtocolLib. I'm eager to try it without this library. Either a hard dependency, or no dependency at all (so we avoid implementing the sign change twice).

**Comment by boy0001** [comment]
The event is for a chunk loading / generating. There's no event for the actual packet being sent unless we use ProtocolLib.

**Comment by bmarwell** [comment]
Yeah, understood. I'd thought to check if there is a sign in the chunkpopulateevent, and then change it. This way it wouldn't be modified before the chunk was sent. I still don't understand why the sign couldn't be modified before sending to the client.

**Comment by bmarwell** [comment]
Just saw the explanation of the IndividualSigns-Plugin. Makes sense. I'm going to implement the onSignSend-Event again, which will be even easier to handle. Again, thanks for the hint.

**Comment by bmarwell** [comment]
The current build is working without any client issues and without protocol lib.
