### ISSUE TITLE
Add support for SQLite backend

### ISSUE THREAD

**Issue by boy0001** [boy0001/ExperienceBankII#5]

**Comment by bmarwell** [comment]
I think, this should be the default backend anyway. It has advantages over flat files (concurrency) and is no-config. 
Also, we might even reuse the SQL statements. Both backends can share a common interface.

**Comment by boy0001** [comment]
Yeah, sqlite is much better than using yml

**Comment by bmarwell** [comment]
Probably because we can have simultaniously R/W access. With yaml we would need locking.
