### ISSUE TITLE
Identify why the hashmap is cleared

### ISSUE THREAD

**Issue by bmarwell** [boy0001/ExperienceBankII#7]
Why clear everything if a location is found?

https://github.com/boy0001/ExperienceBankII/blob/master/src/main/java/com/empcraft/xpbank/InSignsNano.java#L177-L178

**Comment by bmarwell** [comment]
closed by https://github.com/boy0001/ExperienceBankII/commit/46a169345c2219aae265d518c927af8c71f34b78

**Comment by boy0001** [comment]
Not entirely sure since I wrote that code a while ago. Dealing with the quirk of breaking a sign causing it to reappear when updated. The whole class can likely be stripped out if a protocollib depend wants to be used instead.

**Comment by bmarwell** [comment]
Thanks for the comment. This is helpful. You had the update implemented twice, and one of the update methods didn't check for the sign still being there. 

I will test the plugin on my private spigot server as soon as SQLite is done. That's not to far from now.
